# Git Account Switcher for Windows PowerShell
# Usage: .\switch.ps1 aiwithr  OR  .\switch.ps1 raqueeb
# Without args: shows current account status
# Version: 1.0 (May 31, 2026)

param(
    [Parameter(Mandatory=$false)]
    [ValidateSet("aiwithr", "raqueeb", "status")]
    [string]$Account
)

$SSH_DIR = "$env:USERPROFILE\.ssh"
$CONFIG_FILE = "$SSH_DIR\config"

# Check current account from SSH config
$currentConfig = Get-Content $CONFIG_FILE -Raw -ErrorAction SilentlyContinue
$currentAccount = if ($currentConfig -match "id_ed25519_aiwithr") { "aiwithr" } else { "raqueeb" }

# Display current status if no account specified
if (-not $Account -or $Account -eq "status") {
    Write-Host ""
    Write-Host "======================================" -ForegroundColor Yellow
    Write-Host "  Current Account: $currentAccount" -ForegroundColor Cyan
    Write-Host "======================================" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "To switch, run:"
    Write-Host "  .\switch.ps1 aiwithr  (or .\switch.ps1 raqueeb)" -ForegroundColor Green
    Write-Host ""
    exit 0
}

# Check if already on the requested account
if ($Account -eq $currentAccount) {
    Write-Host "Already on: $Account" -ForegroundColor Yellow
    exit 0
}

# Get user home path for SSH keys
$USER_HOME = $env:USERPROFILE
$USER_NAME = $env:USERNAME

# Generate SSH config based on selected account
if ($Account -eq "aiwithr") {
    $config = @"
# GitHub SSH Config - Generated by switch.ps1
# Active Account: aiwithr

# aiwithr account (default for github.com)
Host github.com
    HostName github.com
    User git
    IdentityFile $USER_HOME\.ssh\id_ed25519_aiwithr

# raqueeb account (use raqueeb.github.com)
Host raqueeb.github.com
    HostName github.com
    User git
    IdentityFile $USER_HOME\.ssh\id_ed25519_raqueeb
"@
} else {
    $config = @"
# GitHub SSH Config - Generated by switch.ps1
# Active Account: raqueeb

# raqueeb account (default for github.com)
Host github.com
    HostName github.com
    User git
    IdentityFile $USER_HOME\.ssh\id_ed25519_raqueeb

# aiwithr account (use aiwithr.github.com)
Host aiwithr.github.com
    HostName github.com
    User git
    IdentityFile $USER_HOME\.ssh\id_ed25519_aiwithr
"@
}

# Write config and confirm
Set-Content -Path $CONFIG_FILE -Value $config -Force
Write-Host ""
Write-Host "======================================" -ForegroundColor Green
Write-Host "  Switched to: $Account" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Green
Write-Host ""
Write-Host "Active: github.com uses $Account SSH key"
Write-Host "For specific account repos, use:"
Write-Host "  git clone git@raqueeb.github.com:user/repo.git"
Write-Host "  git clone git@aiwithr.github.com:user/repo.git"